<!DOCTYPE html>
<html>
<head>
    <title>My WebSocket</title>
</head>

<body>
Welcome<br/>
<input id="text" type="text"/>
<button onclick="test()">Send</button>
<button onclick="test()">Close</button>
<div id="message">
</div>
</body>
<script type="text/javascript" src="../js/sockjs.js"></script>
<script type="text/javascript" src="../js/jquery.min.js"></script>
<script type="text/javascript" src="../js/stomp.js"></script>
<script type="text/javascript">
// Generated by CoffeeScript 1.7.1

/*
   Stomp Over WebSocket http://www.jmesnil.net/stomp-websocket/doc/ | Apache License V2.0

   Copyright (C) 2010-2013 [Jeff Mesnil](http://jmesnil.net/)
   Copyright (C) 2012 [FuseSource, Inc.](http://fusesource.com)
 */
    function test(){
	debugger;
        var s = new SockJS('http:localhost:8080/socket');
        var stompClient = Stomp.over(s);
		alert("1");
        stompClient.connect({}, function () {
            console.log('notice socket connected!');
            stompClient.subscribe('/topic/notice', function (data) {
			alert("2");
                alert(data.body);
            });
        });
    }
</script>
</html>